apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.wardle.example.com
spec:
  insecureSkipTLSVerify: true
  group: test.com
  version: v1alpha1
  service:
    name: aggregated-apiserver
    namespace: kube-system
  groupPriorityMinimum: 1000
  versionPriority: 15
---
apiVersion: v1
kind: Service
metadata:
  name: aggregated-apiserver
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    apiserver: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregated-apiserver
  namespace: kube-system
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: api-server
        image: kube-sample-apiserver:latest
        imagePullPolicy: Never
        args: [ "--etcd-servers=http://localhost:2379" ]
